<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/04/23 19:33:28

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=cain',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
